name: todo_list_notifier
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  numberpicker: ^2.1.2
  calendar_date_picker2: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-ExtraLight.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-Light.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-Regular.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-Medium.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-Bold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-ExtraBold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-SemiBold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-Black.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-ExtraLight.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-Light.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-Regular.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-Medium.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-SemiBold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-Bold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-ExtraBold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-Black.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-ExtraLight.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-Light.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-Regular.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-Medium.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-SemiBold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-Bold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-ExtraBold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-Black.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-ExtraLight.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-Light.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-Regular.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-Medium.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-SemiBold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-Bold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-ExtraBold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-Black.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-ExtraLight.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-Light.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-Regular.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-Medium.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-SemiBold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-Bold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-ExtraBold.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-Black.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-ExtraLight.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-Light.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-Regular.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-Medium.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-SemiBold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-Bold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-ExtraBold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-Black.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-ExtraLight.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-Light.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-Regular.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-Medium.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-SemiBold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-Bold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-ExtraBold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-Black.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-ExtraLight.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-Light.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-Regular.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-Medium.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-SemiBold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-Bold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-ExtraBold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-Black.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-ExtraLight.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-Light.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-Regular.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-Medium.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-SemiBold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-Bold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-ExtraBold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-Black.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-ExtraLight.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-Light.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-Regular.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-Medium.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-SemiBold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-Bold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-ExtraBold.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-Black.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-ExtraLightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-LightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-Italic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-MediumItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-SemiBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-BoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Condensed-BlackItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-ExtraLightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-LightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-Italic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-MediumItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-BoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiCondensed-BlackItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-ExtraLightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-LightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-Italic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-MediumItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-SemiBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-BoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt-BlackItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-ExtraLightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-LightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-Italic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-MediumItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-SemiBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-BoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_SemiExpanded-BlackItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-ExtraLightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-LightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-Italic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-MediumItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-SemiBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-BoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_7pt_Expanded-BlackItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-ExtraLightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-LightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-Italic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-MediumItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-SemiBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-BoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Condensed-BlackItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-ExtraLightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-LightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-Italic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-MediumItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-BoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiCondensed-BlackItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-ExtraLightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-LightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-Italic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-MediumItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-SemiBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-BoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt-BlackItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-ExtraLightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-LightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-Italic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-MediumItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-SemiBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-BoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_SemiExpanded-BlackItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-ExtraLightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-LightItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-Italic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-MediumItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-SemiBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-BoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/NunitoSans_10pt_Expanded-BlackItalic.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono/static/RobotoMono-Thin.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-ExtraLight.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-Light.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-Regular.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-Medium.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-SemiBold.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-Bold.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-ThinItalic.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-ExtraLightItalic.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-LightItalic.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-Italic.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-MediumItalic.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-SemiBoldItalic.ttf
        - asset: assets/fonts/roboto_mono/static/RobotoMono-BoldItalic.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
